Fixes issue #2
ken1000minus7/Bloggy pull request #19
Opened 2023-02-07 18:05 UTC by Nikhil7174

## Description

Added new fonts to the website

## Issue Resolved

 Fixes #2.

## Checklist

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

2023-02-07 18:13 UTC, ken1000minus7 requested changes
Hey @Nikhil7174 , you do not need to make changes in the spacing and quotes, please avoid making changes to parts of code that don't need to be touched, I have commented on a few but almost all files need to be fixed

2023-02-07 18:13 UTC, ken1000minus7 commented on src/frontend/src/App.js
> -import Footer from "./components/Footer";
We do not need these spacing changes

2023-02-07 18:13 UTC, ken1000minus7 commented on src/frontend/src/App.js
> -                <Route exact path="/create" element={<CreatePage/>} />
Same here

2023-02-07 18:13 UTC, ken1000minus7 commented on src/frontend/src/components/Navbar.js
> -    },[])
Same in this file

2023-02-07 18:13 UTC, ken1000minus7 commented on src/frontend/src/pages/HomePage.js
> +                )}
This change is unnecessary

2023-02-07 18:13 UTC, ken1000minus7 commented on src/frontend/tailwind.config.js
> +        },
Same for this

2023-02-07 18:42 UTC, Nikhil7174 commented on src/frontend/src/App.js
> -import Footer from "./components/Footer";
I just saved the files in which i made the necessary changes with prettier and later with default document formatter to match the correct indentation. Still this problem is coming. But still will make indentation back to normal.

2023-02-07 19:08 UTC, Nikhil7174 commented
@ken1000minus7 I haven't touched any of these code, i just saved the files after adding new fonts to it using ctrl + s. Tried saving with both prettier and default document formatter. Please suggest me how to bring back the exact indentation back.

2023-02-07 19:27 UTC, ken1000minus7 commented
@Nikhil7174 Well you'll have to rollback the files to fix these changes, and you'll probably hv to change the settings of the prettier extension to disable auto formatting on saving, I hv never used prettier so I am not aware about the settings, you can look up how to change the settings

2023-02-08 04:44 UTC, Nikhil7174 commented
I did the best i could have done, can you please consider this.

2023-02-08 04:45 UTC, Nikhil7174 commented
My dark theme is also almost ready just waiting for this issue to be merged so that i can make a new pull request.

2023-02-08 09:12 UTC, ken1000minus7 commented
@Nikhil7174 The indentations are fixed, great 👌 , just send a screenshot of the page after these changes

2023-02-08 16:58 UTC, Nikhil7174 commented
![Screenshot (114) - Copy](https://user-images.githubusercontent.com/40711348/217598792-c69f5cd6-929d-455e-8be2-68f9cef0f956.png)
![Screenshot (115) - Copy](https://user-images.githubusercontent.com/40711348/217598802-be02759f-05fb-46df-bd6b-665be65a0747.png)
![Screenshot (116) - Copy](https://user-images.githubusercontent.com/40711348/217598808-c61cbb8e-3496-44a0-a2d6-f3b5984cb6c6.png)
![Screenshot (117) - Copy](https://user-images.githubusercontent.com/40711348/217598816-c19f5d81-40b3-48b4-b2fd-439b3de8f1a3.png)

2023-02-08 18:19 UTC, ken1000minus7 approved these changes
Lgtm

2023-02-08 18:19 UTC, merged