Update the Blog
ken1000minus7/Bloggy pull request #26
Opened 2023-02-09 17:40 UTC by ugpec79

## Description

I have created the functionality of updating the blogs

## Issue Resolved
Fixes #9 

## Checklist

Please make sure to review the following before submitting your PR:

- [ x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [ x] I have read the code of conduct.
- [ x] I have reviewed my submission in detail.

2023-02-09 21:37 UTC, ken1000minus7 requested changes
Great work @ugpec79 , need a few changes though
Also share screenshots of the pages changed

2023-02-09 21:37 UTC, ken1000minus7 commented on src/frontend/src/components/Blog.js
> +                </button>
Hide this button when the logged in user is not the author of the blog

2023-02-09 21:37 UTC, ken1000minus7 commented on src/frontend/src/pages/UpdatePage.js
> +                    value={blog.title}
the value here should be `title` , you can set the title to be the blog title when making the get req above, this way initially the title displayed would be the original title, the same can be done for content

2023-02-09 21:37 UTC, ken1000minus7 commented on src/frontend/src/pages/UpdatePage.js
> +            .then(response=> setBlog(response.data))
here u can set the values of `title` and `content`

2023-02-10 08:31 UTC, ugpec79 commented
![image](https://user-images.githubusercontent.com/113056503/218042015-9877407b-b0be-4377-b4b1-8949de13c769.png)

2023-02-10 08:32 UTC, ugpec79 commented
@ken1000minus7 sir I have made changes and the update button in the blog is set inside the if condition already

2023-02-10 08:38 UTC, ugpec79 commented
I was not able to run the backend due to some db issues so I have posted the ji of update page but the updation in data is done

2023-02-10 09:18 UTC, ugpec79 commented
![image](https://user-images.githubusercontent.com/113056503/218052513-5b845697-94a3-479d-917c-c0007db66320.png)

This is for the image which will be seen by the author

2023-02-11 08:20 UTC, ken1000minus7 approved these changes
Lgtm gw, you can tell about the issues with db in the project channel if u r still facing them, I'll see if what can be done

2023-02-11 08:21 UTC, merged

2023-02-11 10:28 UTC, ugpec79 commented
Sir I have re installed everything now it is working fine